version: "3.3" # version of compose format
#version: '3.7'  # version of compose format

services:
  atlas-client:
    build: .
    volumes:
      - ./atlas-client:/usr/src/app # mount point
    ports:
      - 3000:3000 # host:container
    restart: always
