const provinceNameTH = {
  'Chiang Mai': 'เชียงใหม่',
  Lamphun: 'ลำพูน',
  Lampang: 'ลำปาง',
  Uttaradit: 'อุตรดิตถ์',
  Phrae: 'แพร่',
  Nan: 'น่าน',
  Phayao: 'พะเยา',
  'Chiang Rai': 'เชียงราย',
  'Mae Hong Son': 'แม่ฮ่องสอน',
  'Nakhon Sawan': 'นครสวรรค์',
  'Uthai Thani': 'อุทัยธานี',
  'Kamphaeng Phet': 'กำแพงเพชร',
  Tak: 'ตาก',
  Sukhothai: 'สุโขทัย',
  Phitsanulok: 'พิษณุโลก',
  Phichit: 'พิจิตร',
  Phetchabun: 'เพชรบูรณ์',
  'Bueng Kan': 'บึงกาฬ',
  'Nong Khai': 'หนองคาย',
  Loei: 'เลย',
  'Nong Bua Lam Phu': 'หนองบัวลำภู',
  'Udon Thani': 'อุดรธานี',
  'Sakon Nakhon': 'สกลนคร',
  'Nakhon Phanom': 'นครพนม',
  Mukdahan: 'มุกดาหาร',
  Kalasin: 'กาฬสินธุ์',
  Chaiyaphum: 'ชัยภูมิ',
  'Khon Kaen': 'ขอนแก่น',
  'Maha Sarakham': 'มหาสารคาม',
  'Roi Et': 'ร้อยเอ็ด',
  Yasothon: 'ยโสธร',
  'Amnat Charoen': 'อำนาจเจริญ',
  'Ubon Ratchathani': 'อุบลราชธานี',
  'Si Sa Ket': 'ศรีสะเกษ',
  Surin: 'สุรินทร์',
  Buriram: 'บุรีรัมย์',
  'Nakhon Ratchasima': 'นครราชสีมา',
  Bangkok: 'กรุงเทพมหานคร',
  'Nakhon Pathom': 'นครปฐม',
  Nonthaburi: 'นนทบุรี',
  'Pathum Thani': 'ปทุมธานี',
  'Samut Prakan': 'สมุทรปราการ',
  'Samut Sakhon': 'สมุทรสาคร',
  'Samut Songkhram': 'สมุทรสงคราม',
  'Ang Thong': 'อ่างทอง',
  'Phra Nakhon Si Ayutthaya': 'พระนครศรีอยุธยา',
  'Chai Nat': 'ชัยนาท',
  'Lop Buri': 'ลพบุรี',
  'Nakhon Nayok': 'นครนายก',
  Saraburi: 'สระบุรี',
  'Sing Buri': 'สิงห์บุรี',
  Kanchanaburi: 'กาญจนบุรี',
  Phetchaburi: 'เพชรบุรี',
  'Prachuap Khiri Khan': 'ประจวบคีรีขันธ์',
  Ratchaburi: 'ราชบุรี',
  'Suphan Buri': 'สุพรรณบุรี',
  Chachoengsao: 'ฉะเชิงเทรา',
  Chanthaburi: 'จันทบุรี',
  'Chon Buri': 'ชลบุรี',
  'Prachin Buri': 'ปราจีนบุรี',
  Rayong: 'ระยอง',
  'Sa Kaeo': 'สระแก้ว',
  Trat: 'ตราด',
  Chumphon: 'ชุมพร',
  'Nakhon Si Thammarat': 'นครศรีธรรมราช',
  Narathiwat: 'นราธิวาส',
  Pattani: 'ปัตตานี',
  Phatthalung: 'พัทลุง',
  Songkhla: 'สงขลา',
  'Surat Thani': 'สุราษฎร์ธานี',
  Yala: 'ยะลา',
  Krabi: 'กระบี่',
  Phangnga: 'พังงา',
  Phuket: 'ภูเก็ต',
  Ranong: 'ระนอง',
  Satun: 'สตูล',
  Trang: 'ตรัง',
};

export default provinceNameTH;
